from typing import Protocol


class SqlDatabaseInterface(Protocol):
    @property
    def dialect(self) -> str: ...

    def get_table_names(self) -> list[str]: ...

    def get_table_ddl(self, tables: list[str]) -> str: ...

    def get_sample_rows(self, table: str, limit: int) -> str: ...

    def run(self, query: str) -> str: ...