fans = [
    {
        "id": "fan_001",
        "name": "Ciarán Murphy",
        "season_ticket_holder": True,
        "seasons_as_member": 4,
        "matches_attended_2024": 18,
        "matches_attended_2023": 16,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne, Dundalk, Drogheda United, Sligo Rovers",
        "merchandise_purchases": 3,
        "membership_type": "season_ticket",
        "location": "Dublin 6",
        "lapsed": False,
    },
    {
        "id": "fan_002",
        "name": "Aoife Brennan",
        "season_ticket_holder": False,
        "seasons_as_member": 0,
        "matches_attended_2024": 4,
        "matches_attended_2023": 3,
        "derby_matches_only": True,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne",
        "merchandise_purchases": 0,
        "membership_type": "casual",
        "location": "Dublin 7",
        "lapsed": False,
    },
    {
        "id": "fan_003",
        "name": "Seán O'Brien",
        "season_ticket_holder": False,
        "seasons_as_member": 2,
        "matches_attended_2024": 0,
        "matches_attended_2023": 14,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, Dundalk, Drogheda United, Cork City, UCD",
        "merchandise_purchases": 2,
        "membership_type": "lapsed",
        "location": "Dublin 12",
        "lapsed": True,
    },
    {
        "id": "fan_004",
        "name": "Niamh Kelly",
        "season_ticket_holder": False,
        "seasons_as_member": 0,
        "matches_attended_2024": 9,
        "matches_attended_2023": 11,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Dundalk, Drogheda United, Sligo Rovers, Cork City",
        "merchandise_purchases": 1,
        "membership_type": "casual",
        "location": "Dublin 8",
        "lapsed": False,
    },
    {
        "id": "fan_005",
        "name": "Darragh Flynn",
        "season_ticket_holder": True,
        "seasons_as_member": 7,
        "matches_attended_2024": 20,
        "matches_attended_2023": 19,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne, Dundalk, Drogheda United, Sligo Rovers, Cork City, UCD, Derry City",
        "merchandise_purchases": 6,
        "membership_type": "season_ticket",
        "location": "Dublin 14",
        "lapsed": False,
    },
    {
        "id": "fan_006",
        "name": "Fionnuala Daly",
        "season_ticket_holder": False,
        "seasons_as_member": 0,
        "matches_attended_2024": 3,
        "matches_attended_2023": 4,
        "derby_matches_only": True,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne",
        "merchandise_purchases": 0,
        "membership_type": "casual",
        "location": "Dublin 1",
        "lapsed": False,
    },
    {
        "id": "fan_007",
        "name": "Pádraig Whelan",
        "season_ticket_holder": False,
        "seasons_as_member": 3,
        "matches_attended_2024": 0,
        "matches_attended_2023": 12,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, Dundalk, Shelbourne, Derry City",
        "merchandise_purchases": 1,
        "membership_type": "lapsed",
        "location": "Dublin 6W",
        "lapsed": True,
    },
    {
        "id": "fan_008",
        "name": "Eimear Nolan",
        "season_ticket_holder": False,
        "seasons_as_member": 1,
        "matches_attended_2024": 7,
        "matches_attended_2023": 8,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Dundalk, Drogheda United, Cork City",
        "merchandise_purchases": 2,
        "membership_type": "casual",
        "location": "Dublin 6",
        "lapsed": False,
    },
    {
        "id": "fan_009",
        "name": "Tomás Ó Briain",
        "season_ticket_holder": True,
        "seasons_as_member": 5,
        "matches_attended_2024": 17,
        "matches_attended_2023": 15,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne, Dundalk, Drogheda United, Sligo Rovers, UCD",
        "merchandise_purchases": 4,
        "membership_type": "season_ticket",
        "location": "Dublin 16",
        "lapsed": False,
    },
    {
        "id": "fan_010",
        "name": "Roisín Mac Cárthaigh",
        "season_ticket_holder": False,
        "seasons_as_member": 0,
        "matches_attended_2024": 5,
        "matches_attended_2023": 6,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, Dundalk, Drogheda United, Sligo Rovers",
        "merchandise_purchases": 1,
        "membership_type": "casual",
        "location": "Dublin 9",
        "lapsed": False,
    },
    {
        "id": "fan_011",
        "name": "Conor Sheridan",
        "season_ticket_holder": False,
        "seasons_as_member": 0,
        "matches_attended_2024": 2,
        "matches_attended_2023": 2,
        "derby_matches_only": True,
        "opponents_attended": "Bohemian FC, Shelbourne",
        "merchandise_purchases": 0,
        "membership_type": "casual",
        "location": "Dublin 3",
        "lapsed": False,
    },
    {
        "id": "fan_012",
        "name": "Mairéad Ní Fhaoláin",
        "season_ticket_holder": False,
        "seasons_as_member": 2,
        "matches_attended_2024": 11,
        "matches_attended_2023": 10,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne, Dundalk, Drogheda United",
        "merchandise_purchases": 3,
        "membership_type": "casual",
        "location": "Dublin 12",
        "lapsed": False,
    },
    {
        "id": "fan_013",
        "name": "Brian Kavanagh",
        "season_ticket_holder": False,
        "seasons_as_member": 4,
        "matches_attended_2024": 0,
        "matches_attended_2023": 8,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Dundalk",
        "merchandise_purchases": 0,
        "membership_type": "lapsed",
        "location": "Dublin 24",
        "lapsed": True,
    },
    {
        "id": "fan_014",
        "name": "Sinéad Farrell",
        "season_ticket_holder": True,
        "seasons_as_member": 6,
        "matches_attended_2024": 19,
        "matches_attended_2023": 18,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne, Dundalk, Drogheda United, Sligo Rovers, Cork City, Derry City",
        "merchandise_purchases": 5,
        "membership_type": "season_ticket",
        "location": "Dublin 14",
        "lapsed": False,
    },
    {
        "id": "fan_015",
        "name": "Liam de Búrca",
        "season_ticket_holder": False,
        "seasons_as_member": 0,
        "matches_attended_2024": 6,
        "matches_attended_2023": 7,
        "derby_matches_only": False,
        "opponents_attended": "Bohemian FC, St Patricks Athletic, Shelbourne, Dundalk",
        "merchandise_purchases": 2,
        "membership_type": "casual",
        "location": "Dublin 8",
        "lapsed": False,
    },
]